### ISSUE TITLE
Would be nice to port on latest nom

### ISSUE THREAD

**Issue by tim77** [marirs/nparse#3]
Would be nice to port on latest version of  `nom` https://crates.io/crates/nom/versions

Rationale: this could help with packaging `nparse` for official Linux repos.

**Comment by marirs** [comment]
Hi - yes, I'll port it to the latest soon :)
Will update you by weekend for the same

**Comment by tim77** [comment]
Awesome! I would like to help with this only if I could. 😁

**Comment by marirs** [comment]
Its done! :)
